# Generated by Django 4.2.1 on 2023-05-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50)),
                ('is_corrext', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('result', models.CharField(max_length=10)),
                ('options', models.ManyToManyField(to='quiz_api.choice')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.quizmodel'),
        ),
    ]
