# Generated by Django 4.2.1 on 2023-05-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_corrext',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='quizmodel',
            old_name='is_active',
            new_name='active',
        ),
    ]
