# Generated by Django 4.2.1 on 2023-05-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_rename_is_corrext_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='options',
            new_name='choices',
        ),
    ]
